version: "3.8"

services:
  # Frontend Next.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  # Backend Golang service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    networks:
      - app-network

# Define a network for the services to communicate
networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
