version: "3.8"

services:
  # Backend Service
  backend:
    build:
      context: ./s-network/backend
      dockerfile: Dockerfile
    container_name: social-network-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=sqlite:///data/social-network.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    restart: unless-stopped
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./s-network
      dockerfile: Dockerfile
    container_name: social-network-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  social-network:
    driver: bridge
